-- Script SQL para Criar a Tabela de Aparência (White-Label)

-- 1. Cria a tabela aparencia
CREATE TABLE IF NOT EXISTS public.aparencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL DEFAULT 'default' UNIQUE,
    nome_site TEXT NOT NULL DEFAULT 'Slot da Sorte',
    logo_url TEXT,
    favicon_url TEXT,
    cor_primaria TEXT NOT NULL DEFAULT '#00ff66',
    cor_secundaria TEXT NOT NULL DEFAULT '#FFC801',
    titulo_home TEXT NOT NULL DEFAULT 'SINAIS DE SLOT EM TEMPO REAL',
    subtitulo_home TEXT NOT NULL DEFAULT 'A plataforma de sinais mais assertiva do mercado.',
    texto_cta TEXT NOT NULL DEFAULT 'Acessar Plataforma',
    banner_principal_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insere a configuração padrão inicial
INSERT INTO public.aparencia (
    domain,
    nome_site,
    logo_url,
    favicon_url,
    cor_primaria,
    cor_secundaria,
    titulo_home,
    subtitulo_home,
    texto_cta,
    banner_principal_url
) VALUES (
    'default',
    'Slot da Sorte',
    '/logo.webp',
    '/favicon.ico',
    '#00ff66',
    '#FFC801',
    'SINAIS DE SLOT EM TEMPO REAL',
    'A plataforma de sinais mais assertiva do mercado.',
    'Acessar Plataforma',
    '/logo.webp'
) ON CONFLICT (domain) DO NOTHING;

-- 3. Habilita acesso de leitura público para qualquer visitante do site
ALTER TABLE public.aparencia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso de leitura publico para aparencia" 
ON public.aparencia FOR SELECT 
USING (true);

-- 4. Habilita acesso de modificação para usuários autenticados (Admin)
CREATE POLICY "Permitir update para usuarios autenticados" 
ON public.aparencia FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

CREATE POLICY "Permitir insert para usuarios autenticados" 
ON public.aparencia FOR INSERT 
TO authenticated 
WITH CHECK (true);
