-- Migration aprovada e aplicada ao projeto Supabase.
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  source text not null,
  external_id text not null,
  provider text not null,
  provider_normalized text not null,
  name text not null,
  name_normalized text not null,
  source_url text,
  original_image_url text,
  storage_image_path text,
  storage_image_url text,
  original_icon_url text,
  storage_icon_path text,
  storage_icon_url text,
  source_payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  imported_at timestamptz not null default now(),
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_source_provider_external_id_key
    unique (source, provider_normalized, external_id)
);

create index if not exists games_provider_idx
  on public.games (provider_normalized);

create index if not exists games_name_idx
  on public.games (name_normalized);

create index if not exists games_external_id_idx
  on public.games (external_id);

create index if not exists games_provider_name_idx
  on public.games (provider_normalized, name_normalized);

create index if not exists games_frontend_order_idx
  on public.games (provider_normalized, name_normalized, external_id);

alter table public.games enable row level security;
revoke all on table public.games from anon, authenticated;
grant select (
  id,
  source,
  external_id,
  provider,
  provider_normalized,
  name,
  name_normalized,
  storage_image_url,
  storage_icon_url,
  source_updated_at,
  updated_at
) on public.games to anon, authenticated;

grant all privileges on table public.games to service_role;
grant usage, select on sequence public.games_id_seq to service_role;

drop policy if exists "Public games are readable" on public.games;
create policy "Public games are readable"
  on public.games for select
  to anon, authenticated
  using (true);

-- Bucket público somente para assets destinados ao frontend.
-- A chave administrativa continua sendo a única usada para insert/update/delete.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('games', 'games', true, 5242880, array['image/webp', 'image/png', 'image/jpeg', 'image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
